# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sahilsamanta5
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sahil-internship-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sahil-python-serverless

provider:
  name: aws
  runtime: python3.12
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    # call `pip install` inside a container - useful for packages that have native dependencies (scipy et-al)
    dockerizePip: true

    # aws lambda has an after-extraction size limit - with native dependencies we pass the limit quickly
    # zip the requirements and extract them on the fly (see handler.py)
    zip: true
    
functions:
  hello:
    handler: handler.hello
